{% set version = "4.2.1" %}
{% set lib_major_version = "6" %}

package:
  name: mpfr
  version: {{ version }}

source:
  fn: mpfr-{{ version }}.tar.bz2
  url: https://ftp.gnu.org/gnu/mpfr/mpfr-{{ version }}.tar.gz
  sha256: 116715552bd966c85b417c424db1bbdf639f53836eb361549d1f8d6ded5cb4c6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("mpfr") }}
  missing_dso_whitelist:
    - $RPATH/ld64.so.1  # [s390x]
  script_env:
    # Sets values in win_build/CMakeList.txt
    - PROJECT_VERSION={{ version }}                  # [win]
    - LIB_MAJOR_VERSION={{ lib_major_version }}      # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool         # [unix]
    - m4              # [unix]
    - make            # [unix]
  host:
    # https://www.mpfr.org/mpfr-current/mpfr.html#How-to-Install
    - gmp >=5.0.0

test:
  requires:
    - {{ compiler('c') }}
    - libtool         # [unix]
    - m4              # [unix]
  files:
    - test.c
  commands:
    - test -f ${PREFIX}/lib/libmpfr{{ SHLIB_EXT }}.{{ lib_major_version }} || (echo "Failed to find libmpfr{{ SHLIB_EXT }}.{{ lib_major_version }}" && exit 1)  # [linux]
    - test -f ${PREFIX}/lib/libmpfr.{{ lib_major_version }}{{ SHLIB_EXT }} || (echo "Failed to find libmpfr.{{ lib_major_version }}{{ SHLIB_EXT }}" && exit 1)  # [osx]
    - test -f ${PREFIX}/lib/libmpfr{{ SHLIB_EXT }} || (echo "Failed to find libmpfr{{ SHLIB_EXT }}" && exit 2)  # [unix]
    - test -f ${PREFIX}/lib/libmpfr.a || (echo "Failed to find libmpfr.a" && exit 3)                            # [unix]
    - ${CC} -L$PREFIX/lib -I$PREFIX/include -lmpfr -lgmp -Wl,-rpath,$PREFIX/lib $RECIPE_DIR/test.c -o test.o    # [unix]
    - ./test.o                                                                                                  # [unix]
    - if not exist %LIBRARY_INC%\mpfr.h exit 1                               # [win]
    - if not exist %LIBRARY_BIN%\mpfr.dll exit 2                             # [win]
    - if not exist %LIBRARY_BIN%\libmpfr-{{ lib_major_version }}.dll exit 3  # [win]
    - if not exist %LIBRARY_LIB%\libmpfr.dll.a exit 4                        # [win]
    - if not exist %LIBRARY_LIB%\libmpfr.lib exit 5                          # [win]
    - if not exist %LIBRARY_LIB%\mpfr.lib exit 6                             # [win]
    # Test whether libmpfr.dll.a and mpfr.lib work.
    - cl.exe -I%LIBRARY_INC% %RECIPE_DIR%\test.c /Fe"%cd%\test.exe" /link /LIBPATH:"%LIBRARY_LIB%" libmpfr.dll.a  # [win]
    - .\test.exe                                                                                                  # [win]
    - cl.exe -I%LIBRARY_INC% %RECIPE_DIR%\test.c /Fe"%cd%\test.exe" /link /LIBPATH:"%LIBRARY_LIB%" mpfr.lib       # [win]
    - .\test.exe                                                                                                  # [win]

about:
  home: https://www.mpfr.org/
  license: LGPL-3.0-only
  license_file: COPYING.LESSER
  license_family: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
  description: |
    The MPFR library is a C library for multiple-precision floating-point computations with correct rounding. MPFR has
    continuously been supported by the INRIA and the current main authors come from the Caramba and AriC project-teams
    at Loria (Nancy, France) and LIP (Lyon, France) respectively; see more on the credit page. MPFR is based on the GMP
    multiple-precision library.
  doc_url: https://www.mpfr.org/
  dev_url: https://gitlab.inria.fr/mpfr/mpfr

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - marcelotrevisani
