travis:
  secure:
    BINSTAR_TOKEN: lLlLvCLVu3h8zVPpfePVgo0+tUWlYljn4XAJuBlQIOVo6vmiOpKIFHy5iU+4cH5QJ1djNN2l79WzeeYNmUe4tKtzwpR+BMAGDZrhrzCqakDiq/kbmvdKjp1vV72oflTKDZ7BZ29E5OHamNUwWy4lczSAfuHjWRWf52BrF9C6iAYvl1/Un5cARXQwmgus/sOokygLNwaELxFJEMpBfcJJaw2TyqgFuFAxOHZursEcZJEFOsCliIYb+YcW6CzuTI7NLcLJazu64WPGQ/FdFGPWp8ijvc9vla6pIBqDQvKt+MwIFXua+3Q8JJdYoMoqVSNx7gkRfz2if3B75UP1ST9utXFoW/afM/nJnCjBig4HMsTjfvm4obKTben+OgxiWH5V6r55Ye1lF6XtUfnpuVVt5y+pjGXdToS+huRZUhiqRUoC2hDbWxaN8T31jPxzAf3O4keLLaKSrJIRPYOwO1CcsZJ/McM0VGyRim5mC3gWDEy1biKit9WDImTPBUv6dMCvSuooaoSsnNmikP/cLLfsdCQ/7oouElGeB5x+zXYcHQm2IfLlNxjt6ryzmzckZYioa8Xx0YnAnhI83ifcGdf0uQDmaN3enlEYyMp8nzGydx8pOZKt+OWg0OUQRrT+R0WmqCdBEV68oMWzs1D9b+zgSPeIgLOXNT0ov5WhyvrN2E4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
