travis:
  secure:
    BINSTAR_TOKEN: JbLAdKe8XISWx01nWic1Rw2+V59RHaPd5JYZefCL7WMPM2ZzRJsD9XsTbtdg2W5VtxTpFJtRBWrWyB70LGcbhavoADG5NU7LW2+w8QNdnMexLprkkM/NVIa1k/8J5Qs/18Fv8R+Dq0pycBqJ9ffimWpR2uJCpoMCVnrP4LkydRYUrKZ50yUjLMT3gFx6TqCXtP78QHTe31kXmmZHOvcRSErEjJu6F6iVxUXLXY6ztSUbHSZ70eRbtr6GJfSHuUg2Z/mqo0SvL+7i4ViBR7ERXGgV3+wvW5n4DRg9goOFMSkjsemY8aYRNo8+zO65YErBq9raw5ZxUPb6eO0x5bkQdmvsWlyRJ7WN4o+V4t0b2WF8Hfaw/jnqolPBwhnI/xM1ylkbhK/w4G5O1YnwrmuRqNVQLag+osC20qYwMje/TtnziGIDBn++wNiCz53Z3f9z5nnB9fXIZmD/De36azyoz14ZR4q/vMKZt55w/drWM45QCWEzXI5hywQNMB0snzwY3xpolY0tEBInBjHd13Uj9VRIYt1sZJxkcTIlAKEsFUempBEdlV+XW4eFtjbRGH3xqA2r/S3/7J461T0xmB6DkRfbFIAD6cXPwtLSK7mkZXZMTNgY44QFhjBjdHTPs6PGY1y+sC5/V50Q8FBjsv1N7VTMIYIwJKW8tG3j2sYrW5A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
